<?php $_columnCount = $this->getData('item_colcount'); ?>
<?php $_reviews = $this->getReviewsData();?>
<?php $_item_display_type = $this->getData('item_display_type'); ?>

<!-- SLIDER RULE START -->
<?php if ($_item_display_type): ?>
        <div class="easyslider" id="glider<?php echo $this->getData('item_id') ?>">
            
            <div class="controls" >           
                <?php $i=0; foreach($_reviews as $review): ?>            
                    <?php $i++; ?>
                    <a class="slide-nav" href="#section<?php echo $this->getData('item_id').$i; ?>">  Slide #<?php echo $this->getData('item_id').$i; ?></a>
                <?php endforeach; ?>   
            </div>    
            <?php if ($i): ?>                     
                <div class="control-links" >
                    <a class="prev" href="#" onclick="easyglider<?php echo $this->getData('item_id') ?>.previous();return false;">Previous</a>
                    <a class="next" href="#" onclick="easyglider<?php echo $this->getData('item_id') ?>.next();return false">Next</a>                
                </div>          
            <?php endif; ?>    
            
            <div class="scroller">
                <div class="content">   
<?php endif ?>     
<!-- SLIDER RULE END -->                       
            <?php $i=0; $total = count($_reviews); foreach($_reviews as $review): ?>
                <?php 
                    

                    $ratings = $review['ratings'][0];
                    $_product = $review['product'];
                    
                    $i++;
                    $class ='';
                    if ($i == 1) $class ='class="first"';
                    if ($i == $total ) $class ='class="last"';
                ?>
                    <!-- SLIDER RULE START -->
                    <?php if ($_item_display_type): ?>            
                    <div class="section" id="section<?php echo $this->getData('item_id').$i; ?>">
                    <?php endif ?>     
                    <!-- SLIDER RULE END -->       
                <dl <?php echo $class; ?>>
                    <div class="product-image">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(132, 124); ?>" width="132" height="124" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>                    
                    <dt>
                        <a href="<?php echo $review['review_url']; ?>"><?php echo $review['title']; ?></a> <?php echo $this->__('Review by');?> <strong><?php echo $review['nickname']; ?></strong>
                    </dt>
                    <dd>
                        <table class="ratings-table">
                                <col width="1">
                                <col>
                                <tbody>
                                    <?php foreach($ratings as $k => $rating): ?>         
                                        <tr>
                                            <th><?php echo $k;?></th>
                                            <td>
                                                <div class="rating-box">
                                                    <div style="width: <?php echo $rating; ?>%;" class="rating"></div>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>                                    
                                </tbody>
                            </table>
                        <?php echo $review['detail']; ?><br/>


                        <?php if (Mage::getStoreConfig('easybestsellers/options/actions')):?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                <?php echo $this->__('Add to Cart') ?>
                            </button>             

                            <div class="additional-links">    
                                <?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
                                <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php
                                    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
                                ?>
                                <?php if($_compareUrl) : ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                                </ul>   
                            </div>                                            
                        <?php endif; ?>         
                            
                    </dd>
                </dl>
                        <!-- SLIDER RULE START -->
                        <?php if ($_item_display_type): ?>            
                        </div>
                        <?php endif ?>     
                        <!-- SLIDER RULE END -->            
                
            <?php endforeach; ?>
                
            <!-- SLIDER RULE START -->
            <?php if ($_item_display_type): ?>                           

                            </div>
                        </div>
                    </div>
            <script type="text/javascript" charset="utf-8">
                var easyglider<?php echo $this->getData('item_id') ?> = new Glider('glider<?php echo $this->getData('item_id') ?>', {
                                                        duration:<?php echo Mage::getStoreConfig('easybestsellers/slider/animduration') ?>,
                                                        autoGlide:<?php echo Mage::getStoreConfig('easybestsellers/slider/autoplay') ?>,
                                                        frequency:<?php echo Mage::getStoreConfig('easybestsellers/slider/slideduration') ?> });
            </script>
            <?php endif ?>     
            <!-- SLIDER RULE END -->                       
                
            <?php if ($i==0): ?>
                <ol id="easybestsellers-no-products" class="mini-products-list">
                    <li class="item odd">
                        <?php echo Mage::getStoreConfig('easybestsellers/options/noproduct'); ?>
                    </li>
                </ol>
            <?php endif;?>
                
                